sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROPMTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_25a36f4b1f8f_key -iv $encrypted_25a36f4b1f8f_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project pandion-181030
  - gcloud config set compute/zone europe-north1-c
  - gcloud container clusters get-credentials production
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t magnusev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run magnusev/react-test npm run test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master